### ISSUE TITLE
Using the viewer example

### ISSUE THREAD

**Issue by michaelliesenberg** [Archie3d/qpdf#4]
How can i run your viewer example?
I open the .pro on qt creatorn and i build the project with this error:
"cannot find -lqpdf"

**Comment by Archie3d** [comment]
Hi. Make sure you open the top-level .pro file (qpdf.pro), which defines two targets: qpdf library and the viewer (which depends on qpdf library). If you open the internal pdfviewer.pro project, the qpdf library will not be built.

**Comment by michaelliesenberg** [comment]
Hi Acrhied3d,

so i am building against Qt version 5.5.1 and i open now the the qpdf.pro and try to build it.
I get new error messages like:
../qpdflib/libqpdf.so:-1: error: undefined reference to `QWebEnginePage::runJavaScript(QString const&)'"
"../qpdflib/libqpdf.so:-1: error: undefined reference to `QWebEngineView::event(QEvent*)'"
"../qpdflib/libqpdf.so:-1: error: undefined reference to `QWebChannel::registerObject(QString const&, QObject*)'"

I am running Qt on Debian Jessie 64bit. Am i missing some library or do i have to install something?

**Comment by Archie3d** [comment]
Hi Michael,
I've tested the build in Ubuntu 16.04 using Qt 5.8.0 with no issues.
Please make sure you have QtWebEngine installed in your system.
